name: bankingapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  provider: ^6.1.5

  # Animations
  lottie: ^2.6.0

  # UI and Utilities
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  http: ^1.3.0
  shared_preferences: ^2.5.3
  firebase_auth: 5.5.3
  firebase_core: 3.13.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  carousel_slider: ^5.1.1
  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/icons/atm-card.png" # Path to your icon

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/Lottie/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 800

